Repository oveleon/contao-recommendation-bundle, pull requests merged in 2023-07, with the labels that each got.

#12 Support auto-item
  contao/dca/tl_recommendation.php
  contao/dca/tl_recommendation_archive.php
  contao/languages/de/tl_recommendation_archive.xlf
  contao/languages/de/tl_recommendation_list.xlf
  contao/languages/en/tl_recommendation_archive.xlf
  contao/languages/en/tl_recommendation_list.xlf
  contao/modules/ModuleRecommendation.php
  contao/modules/ModuleRecommendationForm.php
  contao/modules/ModuleRecommendationList.php
  src/Model/RecommendationArchiveModel.php
Labels: enhancement

#13 Support auto-item
  README.md
  contao/dca/tl_recommendation.php
  contao/dca/tl_recommendation_archive.php
  contao/languages/de/tl_recommendation_archive.xlf
  contao/languages/de/tl_recommendation_list.xlf
  contao/languages/en/tl_recommendation_archive.xlf
  contao/languages/en/tl_recommendation_list.xlf
  contao/modules/ModuleRecommendation.php
  contao/modules/ModuleRecommendationForm.php
  contao/modules/ModuleRecommendationList.php
  src/Model/RecommendationArchiveModel.php
Labels: bug, enhancement

#14 Fixing the human-readable time output in comments
  contao/modules/ModuleRecommendation.php
Labels: bug
